### ISSUE TITLE
Level 1 Detection Scripts Don't Work

### ISSUE THREAD

**Issue by Wazyre** [Snowyamur/NewtonsHeist#4]
In the first level, if the player drops into the detection cone of the enemies, they don't reset back to a checkpoint. The enemy simply pushes the player away and turns.

This issue isn't replicated in a test scene, detection cones work as intended

**Comment by Snowyamur** [comment]
@Wazyre I think this is resolved, no?

**Comment by Wazyre** [comment]
Right, forgot to close it
